apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notifiers
  namespace: monitoring
data:
  notifiers.yaml: |
    notifiers:
      - name: email-notifier
        type: email
        uid: email1
        org_id: 1
        is_default: true
        send_reminder: true
        frequency: 1h
        settings:
          addresses: mastyka.raman@gmail.com
