service:
  type: NodePort
  port: 3000
  nodePorts:
    grafana: "32020"

persistence:
  enabled: true
  storageClass: "local-path"  # Empty value to use the default StorageClass
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# admin:
#   user: "admin"
#   password: "v9QnhtxvZI"
